import { Menu } from "@/types/menu";

const menuData: Menu[] = [
  {
    id: 1,
    title: "Startseite",
    path: "/",
    newTab: false,
  },
  {
    id: 5,
    title: "Ägypten Urlaub",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "All Inclusive",
        path: "/all-inklusive",
        newTab: false,
      },
      {
        id: 42,
        title: "Pauschalreisen",
        path: "/contact",
        newTab: false,
      },
      {
        id: 43,
        title: "Lastminute",
        path: "/lastminute",
        newTab: false,
      },
      {
        id: 44,
        title: "Städtereisen",
        path: "/blog-sidebar",
        newTab: false,
      },
      {
        id: 45,
        title: "Ägypten Hotels",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Rundreisen",
        path: "/blog-details",
        newTab: false,
      },
    //  {
    //    id: 46,
    //    title: "Sign In Page",
    //    path: "/signin",
   //     newTab: false,
   //   },
   //   {
     //   id: 47,
     //   title: "Sign Up Page",
     //   path: "/signup",
     //   newTab: false,
     // },
      {
        id: 48,
        title: "Sporturlaub",
        path: "/error",
        newTab: false,
      },
      {
        id: 45,
        title: "Sprachreisen",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Nilkreuzfahrt",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Nassersee-Kreuzfahrt",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Individualreisen",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Unterkünfte",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Mietwagen",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Fähren Ägypten",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Flüge Ägypten",
        path: "/blog-details",
        newTab: false,
      },
    ],
  },
  {
    id: 5,
    title: "Freizeitaktivitäten",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "Kameltouren",
        path: "/about",
        newTab: false,
      },
      {
        id: 42,
        title: "Shopping",
        path: "/contact",
        newTab: false,
      },
      {
        id: 43,
        title: "Shisha-Bars",
        path: "/blog",
        newTab: false,
      },
      {
        id: 44,
        title: "Tauchen",
        path: "/blog-sidebar",
        newTab: false,
      },
      {
        id: 45,
        title: "Surfen",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Schnorcheln",
        path: "/blog-details",
        newTab: false,
      },
    //  {
    //    id: 46,
    //    title: "Sign In Page",
    //    path: "/signin",
   //     newTab: false,
   //   },
   //   {
     //   id: 47,
     //   title: "Sign Up Page",
     //   path: "/signup",
     //   newTab: false,
     // },
      {
        id: 48,
        title: "Wasserski",
        path: "/error",
        newTab: false,
      },
      {
        id: 45,
        title: "Segeln",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Golf",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Tennis",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Quad Saffari",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Jeepsafari",
        path: "/blog-details",
        newTab: false,
      },
      {
        id: 45,
        title: "Freizeitparks",
        path: "/blog-details",
        newTab: false,
      },
    ],
  },
  {
    id: 5,
    title: "Reiseführer",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "Land und Leute",
        path: "/about",
        newTab: false,
      },
      {
        id: 42,
        title: "Die schönsten Strände",
        path: "/contact",
        newTab: false,
      },
      {
        id: 43,
        title: "Kultur und Geschichte",
        path: "/blog",
        newTab: false,
      },
      {
        id: 44,
        title: "Geografie",
        path: "/blog-sidebar",
        newTab: false,
      },
      {
        id: 45,
        title: "Sehenswürdigkeiten & Attraktionen",
        path: "/blog-details",
        newTab: false,
      },
    //  {
    //    id: 46,
    //    title: "Sign In Page",
    //    path: "/signin",
   //     newTab: false,
   //   },
   //   {
     //   id: 47,
     //   title: "Sign Up Page",
     //   path: "/signup",
     //   newTab: false,
     // },
    ],
  },
  {
    id: 5,
    title: "Reisetipps",
    newTab: false,
    submenu: [
      {
        id: 41,
        title: "Einreisebestimmungen",
        path: "/about",
        newTab: false,
      },
      {
        id: 42,
        title: "Zollbestimmungen",
        path: "/contact",
        newTab: false,
      },
      {
        id: 43,
        title: "Reisekalender",
        path: "/blog",
        newTab: false,
      },
      {
        id: 44,
        title: "Reisewörterbuch",
        path: "/blog-sidebar",
        newTab: false,
      },
      {
        id: 45,
        title: "Trinkgeld / Bakschisch",
        path: "/blog-details",
        newTab: false,
      },
    //  {
    //    id: 46,
    //    title: "Sign In Page",
    //    path: "/signin",
   //     newTab: false,
   //   },
   //   {
     //   id: 47,
     //   title: "Sign Up Page",
     //   path: "/signup",
     //   newTab: false,
     // },
      {
        id: 48,
        title: "Ansprechpartner",
        path: "/error",
        newTab: false,
      },
      {
        id: 48,
        title: "Wetter in Ägypten",
        path: "/error",
        newTab: false,  
        
      },
    ],
  },
];
export default menuData;
